twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        pub_key: '%env(UPLOADCARE_PUBLIC_KEY)%'

when@test:
    twig:
        strict_variables: true
